/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  Drupal.color = {
    logoChanged: false,
    callback: function callback(context, settings, $form) {
      if (!this.logoChanged) {
        $('.color-preview .color-preview-logo img').attr('src', drupalSettings.color.logo);
        this.logoChanged = true;
      }

      if (drupalSettings.color.logo === null) {
        $('div').remove('.color-preview-logo');
      }

      var $colorPreview = $form.find('.color-preview');
      var $colorPalette = $form.find('.js-color-palette');

      $colorPreview.css('background-color', $colorPalette.find('input[name="palette[bg-base]"]').val());
      $colorPreview.css('color', $colorPalette.find('input[name="palette[text-color]"]').val());

      var $colorPreviewMain = $form.find('.color-preview-main');
      var $colorPreviewLinks = $colorPreviewMain.find('a');
      $colorPreviewLinks.css('color', $colorPalette.find('input[name="palette[link-color]"]').val());

    }
  };
})(jQuery, Drupal, drupalSettings);